### ISSUE TITLE
Jails / Add / Wizard -> IPv6 interface should allow none as option

### ISSUE THREAD

**Issue by k2patel** [freenas/webui#1097]
iocage does support option to set IPv6 Interface to none, which appear to disable IPv6 support.
Current interface doesn't allow that as option, it doesn't allow me to click next.

**Comment by erinix** [comment]
Could you please file this as a bug on our Redmine tracker https://redmine.ixsystems.com

**Comment by erinix** [comment]
https://redmine.ixsystems.com/issues/42797 I wasn't sure if you ever made a ticket for this so I created one for you.  Please follow this ticket for updates
