### ISSUE TITLE
pluggins/jails Management button ip redirection

### ISSUE THREAD

**Issue by d-rav3n** [freenas/webui#1193]
Hi,
Just wanted to let you know what I noticed using freenas 11.2.
1.- After installing a plugin (tested with plex and syncthing) it creates one jail for each plugin which boots in dhcp ip mode. In this situation, when you go to plugins -> installed and select "management" in each of them, you get to the web interface of the selected jail in a new tab and works as spected.

The problem comes when you configure the jail (any of them) to have a static ip with its netmask and gateway. In that case, if you go again to plugins -> installed and select "management" in any of them you get redirected to "http://$static_ip_address/$net_mask:$port/$whatever" which drives you to an not_found_error_page.

Just to clarify, in the case of plex it would be something like "http://192.168.1.175/24:32400/web" instead of  "http://192.168.1.175:32400/web" which is the working one.

Hope it makes sense and helps you solve it, which should be an easy one i believe ;PPP

Thank you for and excellent piece of software!

**Comment by erinix** [comment]
I created a ticket with this information on our redmine tracker:

https://redmine.ixsystems.com/issues/42791
