### ISSUE TITLE
Use vectorised graphics (SVG) for logos and artwork

### ISSUE THREAD

**Issue by davidjb** [freenas/webui#168]
High-DPI screens are extremely commonplace, featuring in all major smartphones and tablets, and being adopted by more and more laptop and desktop machines for their displays.  

At present, the use of low-resolution rasterised PNG images for UI elements such as the FreeNAS/TrueNAS/iX logos, the close button (`cancel.png`) and so on, results in the images appearing pixellated on these types of screens.  This is easily fixed with the use of vectorised graphics in the form of [SVGs](https://svgontheweb.com/).  Replacement SVGs, created from the original vector artwork, could be dropped into place and used anywhere the existing `.png` files are.  This then means images are infinitely scalable, transparent, able to be styled in-browser, and typically much smaller than the rasterised counterparts.

SVGs are supported in more browsers than Angular 4 supports (https://caniuse.com/#feat=svg) so there will be no issue with compatibility. 

Can these images be changed over to SVGs?

**Comment by vaibhav-rbs** [comment]
please open up feature request on bugs.freenas.org.

**Comment by davidjb** [comment]
@vaibhav-rbs Opened the feature request at https://redmine.ixsystems.com/issues/27828.
