### ISSUE TITLE
cannot enter multiple ip addresses in Jail config

### ISSUE THREAD

**Issue by tspr** [freenas/webui#1897]
I need to set up a jail with multiple ip addresses. Following the suggestion in the ui tooltip, i cannot save the jail config, since the ip address line is being detected as faulty as soon as the ip address line contains the comma for separating the ip addresses. This is shown by the red colour of the underline. Save button is greyed out and cannot be used.

FreeNAS-11.2-RELEASE-U1
(Build Date: Dec 20, 2018 22:41)

Vivaldi | 2.2.1388.37 (Stable channel) (64-Bit)
-- | --
Überarbeitung | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
Betriebssystem | Linux
JavaScript | V8 7.1.302.31
Flash | 32.0.0.114 /home/ts/.config/google-chrome/PepperFlash/32.0.0.114/libpepflashplayer.so
User-Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 Vivaldi/2.2.1388.37

**Comment by skarekrow** [comment]
Erin: MW works fine here, UI validation is at fault

**Comment by erinix** [comment]
I have created a ticket to keep track of this, see https://redmine.ixsystems.com/issues/83684,

Thanks for your input
