### ISSUE TITLE
can i translate freenas to korean?

### ISSUE THREAD

**Issue by Kimbyeoungjang** [freenas/webui#2038]
i think  src/assets/i18n/ko.po <- that is a korean language file. 
If i want to translate to korean, just fill a msgstr with a korea language?

**Comment by dingyifei** [comment]
I believe this is the right file
You can use a .po editor or a CAT software like omegaT to edit it
Note: stable and master branch’s *.po is slightly different

**Comment by Kimbyeoungjang** [comment]
Then, Which .po files is correct for next update? Master? Or stable

**Comment by erinix** [comment]
For 11.2 you will want to make a PR against freenas/11.2-stable

**Comment by erinix** [comment]
However master is also important because it will show up in future releases

**Comment by Kimbyeoungjang** [comment]
Then, i’ll transate both files lol

When i want to update po files, how to upload po files on this project?

**Comment by erinix** [comment]
Yes that is what I would recommend, please make PRs against both branches freenas/11.2-stable and master and I will review and merge

**Comment by Kimbyeoungjang** [comment]
Ok thanks bro! I’ll close this issue!
