### ISSUE TITLE
Add note to the i18n file.

### ISSUE THREAD

**Issue by OrwillT** [freenas/webui#2144]
Hi.
I just started the Chinese translate mission for the new webui. After translated the words that have only one translation in Chinese, I found it's getting harder than harder to translate. Especially words that have different meanings in different situations, It's really hard for me to make sure which situations it will be with only single line. I try to find some note to help me make this work easier and more accurate but there is even no one line of note. So could you guys add note to the i18n file to help the translation job?
Best wishes.

**Comment by erinix** [comment]
We can look into that but no promises, the po files are auto generated so any manually added notes would get dropped

**Comment by dingyifei** [comment]
@wblock I'm working on simplified Chinese translation too. You can join my translation. I have a server to compile Freenas with up to date zh-hans.po file to see the results.
