### ISSUE TITLE
Unable to enter Plugin, UI error occurs

### ISSUE THREAD

**Issue by jasoncheng7115** [freenas/webui#2294]
Hi,

An error occurs when you are unable to access the Plugin functionality. I am not sure if this is a UI issue.

In addition, for the two strings "Available" and "Installed" in the Plugin function, I can't find them in zh-hant.po for translation.

Thanks.

![2019-05-10 14_24_14-FreeNAS - 172 16 1 236](https://user-images.githubusercontent.com/30381035/57506842-9b705c00-732f-11e9-8b6e-20a5792ffacd.png)

**Comment by erinix** [comment]
Translation part probably just needs markers, while most of the UI is marked properly there are little bits here and there that need to be checked, I intend to have a sweep of these when we get more cycles.  That traceback on the other hand is likely a middleware issue, what version are you using?

**Comment by jasoncheng7115** [comment]
Update to "freenas-11.3-master-201909051123" he is back to normal and ready to use.

**Comment by erinix** [comment]
This issue does indeed seem to be gone, closing issue
