### ISSUE TITLE
Network interfaces dialog is unclear

### ISSUE THREAD

**Issue by k4kfh** [freenas/webui#2348]
When I was setting up a system with the new UI last night, I noticed that there is no clear indication that the boxed area in the network interfaces config represents IP aliases. It looks like just a box with a second set of IP settings in it. It's the small usability things like this that FreeNAS is lacking right now...the new UI looks pretty, it just doesn't feel as solid and reliable yet.

**Comment by erinix** [comment]
Which version are you using?

**Comment by k4kfh** [comment]
11.2-U4.1. This is a fresh install right off the ISO on the website.

**Comment by erinix** [comment]
This field should change in 11.3, all "aliases" will be at the bottom and just called "IP Addresses.  Try a nightly if you wish to see what it currently looks like although I have also a ticket recently to make it even more userfriendly, see https://jira.ixsystems.com/browse/NAS-102000
