### ISSUE TITLE
Process continuity issue via UI.

### ISSUE THREAD

**Issue by MichelDiz** [freenas/webui#3106]
When I do an UPDATE operation. To update the system as a whole in "System -> Update". The information appears

```
Update
62.50%
Installing base-os (1/4)
```

However, when the UI happens to disconnect. The information does not continue (Or the process is extremely slow) and there is no easy way to resume these update logs. And there is no log inside FreeNAS that says "Update is happening".

Improving this interaction would be nice.

**Comment by erinix** [comment]
This should be improved in 11.3, please try the current RC or wait for Release
