### ISSUE TITLE
[Feature] Angular Cli with AOT

### ISSUE THREAD

**Issue by Steven-Harris** [freenas/webui#5]
Greetings, I am software engineer and I love to use freenas. I have a lot of experience with Angular and I wanted to offer my services. It looks like you have forked the ng2-admin project. I am not sure what areas you need help in but I think you all might benefit from using the angular cli. Also, for production you will see an huge increase to performance if you export using Ahead of time compilation. I see AOT in your project file but it doesn't look like it is implemented  at all. I might be able to help you write some ui tests or integration with travis to keep everything working. 

Let me know if you want help,
@mactanxin @william-gr @lola27 @jnix3 @vaibhav-rbs

**Comment by erinix** [comment]
Hello there Steven, those sound like some great ideas and we would be happy to work with you.  If you would like to contribute please create some pull requests and then we will review them and pull them in.  If you need any assistance please feel free to contact me, my email address is erin 'at' ixsystems.com.  I look forward to seeing your work :)

**Comment by darekulti** [comment]
Hey guys, I'm also an engineer, in South Florida. I've got about a year experience with angular in particular and i've used ng2-admin for a few of my own projects in the past. I've been using FreeNAS for a few years now and would also be happy to contribute. @Steven-Harris it would be cool to get in touch and see if we can work together on some this stuff.

Cheers!

**Comment by murac** [comment]
Hey guys, I’m also an engineer, in South Florida. I’ve got about a year experience with angular in particular and i’ve used ng2-admin for a few of my own projects in the past. I’ve been using FreeNAS for a few years now and would also be happy to contribute. @Steven-Harris it would be cool to get in touch and see if we can work together on some this stuff.

Cheers!

**Comment by Steven-Harris** [comment]
No problem! Feel free to contact me!  stevenharrisdev@gmail.com

**Comment by Steven-Harris** [comment]
#6 completed, closing issue
